import configparser
import os

import alembic.command as ac
from alembic.config import Config


# Resolves absolute references to alembic.ini
def _path_resolver(path):
    path = os.path.abspath(path)

    if os.path.exists(path):
        return path

    print(f"Invalid path {path}")
    return None


# Sets the sqlalchemy.url in alembic.ini to locate the database
def alembic_engine(engine, ini_path):
    ini_path = _path_resolver(ini_path)

    if ini_path is not None:
        engine_url = str(engine.url)
        config = configparser.ConfigParser()
        config.read(ini_path)
        # In the .ini file in the alembic section, set sqlalchemy.url equal to the engine's url
        config.set("alembic", "sqlalchemy.url", engine_url)
        with open(ini_path, "w", encoding="utf-8") as file:
            config.write(file)


# Sets the script_location in alembic.ini to locate alembic directory
def alembic_location(ini_path, directory_path):
    ini_path = _path_resolver(ini_path)
    directory_path = _path_resolver(directory_path)

    if ini_path is not None and directory_path is not None:
        config = configparser.ConfigParser()
        config.read(ini_path)
        # In the .ini file in the alembic section, set script_location equal to the alembic directory
        config.set("alembic", "script_location", directory_path)
        with open(ini_path, "w", encoding="utf-8") as file:
            config.write(file)


# Creates autogenerated revisions and upgrades the database
def alembic_revision(ini_path):
    ini_path = _path_resolver(ini_path)

    if ini_path is not None:
        alembic_config = Config(ini_path)
        # Generate revisions for table modifications
        ac.revision(alembic_config, autogenerate=True)
        # Upgrade the db to reflect the most recent revision (heads)
        ac.upgrade(alembic_config, revision="heads")
