"""empty message

Revision ID: 3fbd91a16929
Revises: d756c6cc1811
Create Date: 2024-05-21 17:55:18.212086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = '3fbd91a16929'
down_revision: Union[str, None] = 'd756c6cc1811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('new', sa.Column('nw_column', sa.Boolean(), nullable=True))
    op.drop_column('new', 'new_column')
    op.add_geospatial_column('places', sa.Column('geom', Geometry(geometry_type='POINT', spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.drop_geospatial_index('idx_places_heck', table_name='places', postgresql_using='gist', column_name='heck')
    op.create_geospatial_index('idx_places_geom', 'places', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.drop_geospatial_column('places', 'heck')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_geospatial_column('places', sa.Column('heck', Geometry(geometry_type='POINT', spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), autoincrement=False, nullable=True))
    op.drop_geospatial_index('idx_places_geom', table_name='places', postgresql_using='gist', column_name='geom')
    op.create_geospatial_index('idx_places_heck', 'places', ['heck'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.drop_geospatial_column('places', 'geom')
    op.add_column('new', sa.Column('new_column', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('new', 'nw_column')
    # ### end Alembic commands ###
