"""empty message

Revision ID: 4e85dca7542d
Revises: 1d121de089ed
Create Date: 2024-05-21 17:01:18.201818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e85dca7542d'
down_revision: Union[str, None] = '1d121de089ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subplaces')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subplaces',
    sa.Column('foreign', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('extended', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['foreign'], ['places.id'], name='subplaces_foreign_fkey')
    )
    # ### end Alembic commands ###
