"""empty message

Revision ID: 8d7545575ca0
Revises: 3fbd91a16929
Create Date: 2024-05-21 17:55:58.515507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d7545575ca0'
down_revision: Union[str, None] = '3fbd91a16929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('new', sa.Column('even_even_more', sa.Boolean(), nullable=True))
    op.drop_column('new', 'nw_column')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('new', sa.Column('nw_column', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('new', 'even_even_more')
    # ### end Alembic commands ###
