"""empty message

Revision ID: d756c6cc1811
Revises: 4e85dca7542d
Create Date: 2024-05-21 17:12:39.712720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd756c6cc1811'
down_revision: Union[str, None] = '4e85dca7542d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('new', sa.Column('new_column', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('new', 'new_column')
    # ### end Alembic commands ###
